# Site settings
name: Jekyll Nested Collections Example
title: Jekyll Nested Collections Example
description: "Demo of nesting collections in Jekyll."
baseurl: "https://paddyforan.github.io/jekyll-nested-collections-example"

collections:
        sections:
                output: true
        chapters:
                output: true

# Build settings
markdown: kramdown
permalinks: pretty
